spring.application.name=cats

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${DATABASE_URL}

spring.datasource.username=${DATABASE_USERNAME}

spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.open-in-view=false